### ISSUE TITLE
下载了你的ssr 项目但是跑不起来

### ISSUE THREAD

**Issue by hujialianghuwei** [193Eric/blog#10]
npm run dev 的时候报错了 文件加载不出来 可能是路径不对

**Comment by 193Eric** [comment]
你可以截图错误信息给我看看吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bluceHu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 中午11:34
收件人:&nbsp;"193Eric/blog"<blog@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[193Eric/blog] 下载了你的ssr 项目但是跑不起来 (#10)




npm run dev 的时候报错了 文件加载不出来 可能是路径不对

**Comment by hujialianghuwei** [comment]
务已开启
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
./src/main.js
Module not found: Error: Can't resolve './store' in '/Users/zou/Downloads/blog-master/vue/SSR/ssr/src'
resolve './store' in '/Users/zou/Downloads/blog-master/vue/SSR/ssr/src'
  using description file: /Users/zou/Downloads/blog-master/vue/SSR/ssr/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/zou/Downloads/blog-master/vue/SSR/ssr/package.json (relative path: ./src)
    using description file: /Users/zou/Downloads/blog-master/vue/SSR/ssr/package.json (relative path: ./src/store)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store is not a file
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store.js doesn't exist
      .vue
        Field 'browser' doesn't contain a valid alias configuration
        /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store.vue doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store.json doesn't exist
      as directory
        existing directory
          using path: /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store/index
            using description file: /Users/zou/Downloads/blog-master/vue/SSR/ssr/package.json (relative path: ./src/store/index)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store/index doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store/index.js doesn't exist
              .vue
                Field 'browser' doesn't contain a valid alias configuration
                /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store/index.vue doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /Users/zou/Downloads/blog-master/vue/SSR/ssr/src/store/index.json doesn't exist

**Comment by hujialianghuwei** [comment]
main.js  把import { createStore } from "./store/" 改成 import { createStore } from "./store/store";就可以了

**Comment by 193Eric** [comment]
.. 谢谢了哈，我待会改下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bluceHu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 中午11:41
收件人:&nbsp;"193Eric/blog"<blog@noreply.github.com&gt;;
抄送:&nbsp;"373986529"<373986529@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [193Eric/blog] 下载了你的ssr 项目但是跑不起来 (#10)




main.js  把import { createStore } from "./store/" 改成 import { createStore } from "./store/store";就可以了
